apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-nodejs-app
spec:
  selector:
    matchLabels:
      app: pipeline-nodejs-app
  replicas: 1
  template:
    metadata:
      labels:
        app: pipeline-nodejs-app
    spec:
      containers:
      - name: pipelines-javascript-docker
        image: pipelines-javascript-docker
        imagePullSecret: regcred
        ports:
        - containerPort: 80
